### ISSUE TITLE
How to open desired page directly

### ISSUE THREAD

**Issue by IhorKlimov** [avioli/uni_links#1]
I'm too lazy to experiment, but have you figured a way to open desired page without opening a home page before it (on all platforms)? Currently, I have home page opening and then the one that I want

**Comment by avioli** [comment]
There might be a way for android with its intents, but not for iOS. You could do something in Objective-C (or Swift) by editing the AppDelegate file. Can't help you with this, since this is not the purpose of this plugin.

In Flutter you may be able to make an async main function and add logic there.

Good luck.
