### ISSUE TITLE
Trouble getting the plugin to provide url at startup.

### ISSUE THREAD

**Issue by pneves001** [avioli/uni_links#9]
Hi, I'm having trouble getting the uni_links plugin to provide the URI at startup using getInitialLink. While I can get it to trigger an event using a stream this doesn't work when the app is first open.  I'm not sure if its a problem with the plugin or if I'm not doing something right.  Could I get some help. I'm not getting any errors. the getInitialLink function is just returning null.

**Comment by avioli** [comment]
Are you using the plugin with https:// URIs or custom scheme?

**Comment by pneves001** [comment]
custom uri scheme.

**Comment by avioli** [comment]
Custom URI schemes are the easiest. They can be easily tested with little effort. They also work fine on the iOS Simulator.

Follow the guide in the (README.md)[https://github.com/avioli/uni_links#for-ios] line by line.

Here's the checklist:

- [ ] Declare your Custom URI scheme in `ios/Runner/Info.plist`;
- [ ] Add dart code for Initial Link (and on-change event);
- [ ] Run app and quit/detach;
- [ ] Ensure the app has terminated on the simulator/device by checking the recently used apps (aka app switcher). If not - flick it up to terminate it;
- [ ] Run any of the [testing commands from the README.md](https://github.com/avioli/uni_links#ios).

NOTE: The simulator/device _may_ ask you if you want to open the link in the app.

The most common problem is that you cannot get the initial link, unless the app was terminated and then started, because of the Custom URI Link.

If you still have problems - clone the repo and open up the example project - it is setup for Custom URI scheme. Run the example app, terminate it and run any of the testing commands.

**Comment by pneves001** [comment]
The plugin works once the app is loaded. If I run the app and then open up the link from a browser it works. It doesn't work if the app is not loaded and we load the app by clicking on the link. Then it just loads the app but doesn't return the initial link or execute the on change event. 

I'm using an Ipod touch for my device, not the simulator.

**Comment by pneves001** [comment]
I've tried what you've mentioned here as what I should do. Its not working. It won't provide the URI on launch. It works if the app is already loaded. But not on launch.

**Comment by avioli** [comment]
![uni_links ios demo with custom uri scheme](https://user-images.githubusercontent.com/524259/46118759-79681480-c24b-11e8-9287-a06109da28cc.gif)

**Comment by pneves001** [comment]
Thanks for the help. I think I just found the problem I was having. It was an issue with asynchronous function calls. not executing in time.

**Comment by avioli** [comment]
Just fyi - initial link should be ALWAYS the same if the app was started with one, no matter how late you request it.

**Comment by pneves001** [comment]
thanks. I'll keep that in mind.
